
let btn_1 = document.getElementsByClassName('btn_1')[0]
let btn_2 = document.getElementsByClassName('btn_2')[0]
let btn_nav = document.getElementsByClassName('btn_nav')[0]
let body = document.getElementsByClassName('Body')[0]
let nav = document.getElementsByClassName('nav')[0]
let nav2 = document.getElementsByClassName('nav')[1]
let nav3 = document.getElementsByClassName('nav')[2]
let nav4 = document.getElementsByClassName('nav')[3]
let nav5 = document.getElementsByClassName('nav')[4]
let nav6= document.getElementsByClassName('nav')[5]
let paragraphe_1 = document.getElementsByClassName('paragraphe_1')[0]
let center = document.getElementsByClassName('center')[0]
let navbar = document.getElementsByClassName('navbar')[0]
let t1= document.getElementsByClassName('t1')[0]
let t2= document.getElementsByClassName('t1')[1]
let t3= document.getElementsByClassName('t1')[2]
let txt1 = document.getElementsByClassName('txt')[0]
let txt2 = document.getElementsByClassName('txt')[1]
let txt3 = document.getElementsByClassName('txt')[2]
let section = document.getElementsByClassName('section_JS')[0];
let titres= document.createElement('h1');
let creationDiv = document.createElement('div');
let creationDiv1 = document.createElement('div');
let creationDiv2 =document.createElement('div');
let creationDiv3 =document.createElement('div');
let textes = document.createTextNode('Recent Products')
let textes1=document.createTextNode('Luxury Sofa')
let textes2=document.createTextNode('$600.00')
let textes3=document.createTextNode('Leather Gloves')
let textes4=document.createTextNode('$27.00')
let textes5=document.createTextNode('colorful Bowl')
let textes6=document.createTextNode('$18.00')
let textes7=document.createTextNode('$34.00')
let para=document.createElement('p')
let para1=document.createElement('p')
let para2=document.createElement('p')
let para3=document.createElement('p')
let para4=document.createElement('p')
let para5=document.createElement('p')
let para6 =document.createElement('p')
let img = document.createElement("img");
let img1 = document.createElement("img");
let img2= document.createElement("img");
let img3= document.createElement("img");
let grande_div = document.createElement('div')
let super_grande=document.createElement('div')
let div_flex=document.createElement('div')
let div_flex2=document.createElement('div')
let double_div =document.createElement('div')
let div_10=document.createElement('div')
let img10=document.createElement('img')
let div_11=document.createElement('div')
let img11=document.createElement('img')
let div_12=document.createElement('div')
let img12=document.createElement('img')
let grande_div2 =document.createElement('div')
let grande_div3 =document.createElement('div')
let titres2= document.createElement('p')
let titres3= document.createElement('p')
let titres4= document.createElement('p')
let texte2=document.createTextNode('women Bag')
let texte3=document.createTextNode('minimal T-Shirt')
let texte4=document.createTextNode('Plates Set')
let div_13= document.createElement('div')
let div_14= document.createElement('div')
let div_15=document.createElement('div')

let titres5= document.createElement('p')
let titres6= document.createElement('p')
let titres7= document.createElement('p')
let texte5=document.createTextNode('$350.00')
let texte6=document.createTextNode('$15.00')
let texte7=document.createTextNode('$30.00')
let div_17= document.createElement('div')
let div_18= document.createElement('div')
let div_19=document.createElement('div')
let grande_div4 =document.createElement('div')

let div_20=document.createElement('div')
let titres8= document.createElement('p')
let texte8=document.createTextNode('$420.00')
let grande_div5 =document.createElement('div')

export default{
    btn_1,
    btn_2,
    btn_nav,
    body,
    nav,
    nav2,
    nav3,
    nav4,
    nav5,
    nav6,
    paragraphe_1,
    center,
    navbar,
    t1,
    t2,
    t3,
    txt1,
    txt2,
    txt3,
    section,
    titres,
    creationDiv,
    textes,
    img,
    img1,
    creationDiv1,
    creationDiv2,
    textes1,
    para,
    para1,
    para4,
    para5,
    textes2,
    img2,
    img3,
    grande_div,
    para2,
    textes3,
    textes4,
    para3,
    textes5,
    textes6,
    creationDiv3,
    super_grande,
    para6,
    textes7,
    div_flex,
    div_flex2,
    double_div,
    div_10,
    img10,
    div_11,
    img11,
    div_12,
    img12,
    grande_div2,
    titres2,
    titres3,
    titres4,
    texte2,
    texte3,
    texte4,
    div_13,
    div_14,
    div_15,
    grande_div3,
    titres5,
    titres6,
    titres7,
    texte5,
    texte6,
    texte7,
    div_17,
    div_18,
    div_19,
    grande_div4,
    titres8,
    texte8,
    grande_div5,
    div_20
    }


